package by.mluvse.javabot.enums;

public enum UserState {
    IDLE("IDLE"),
    WAITING_GENDER("WAITING_GENDER"),
    WAITING_AGE("WAITING_AGE"),
    WAITING_WEIGHT("WAITING_WEIGHT"),
    WAITING_HEIGHT("WAITING_HEIGHT"),
    WAITING_GOAL("WAITING_GOAL"),
    WAITING_ACTIVITY_TYPE("WAITING_ACTIVITY_TYPE"),

    WAITING_STEPS("WAITING_STEPS"),
    WAITING_WORKOUTS_PER_WEEK("WAITING_WORKOUTS_PER_WEEK"),
    WAITING_WORKOUT_DURATION("WAITING_WORKOUT_DURATION"),
    WAITING_REST_COEFFICIENT("WAITING_REST_COEFFICIENT"),

    SHOWING_RESULT("SHOWING_RESULT"),

    WAITING_MEAL_INPUT("WAITING_MEAL_INPUT"),
    WAITING_MEAL_PHOTO("WAITING_MEAL_PHOTO"),
    WAITING_MEAL_TYPE("WAITING_MEAL_TYPE");

    UserState(String name) {
    }
}
