spring.application.name=TelegramBotFoodTracker
bot.token= ${BOT_TOKEN}

spring.datasource.url=jdbc:postgresql://localhost/telegram_bot
spring.datasource.username=postgres
spring.datasource.password=root

spring.liquibase.change-log=change/db.changelog-master.yaml
logging.level.org.springframework.boot.autoconfigure.liquibase=DEBUG
logging.level.liquibase=DEBUG
spring.liquibase.enabled=true

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect